flags:
  ide-backend-yesod: {}
packages:
- '.'
- '../ide-backend/ide-backend'
- '../ide-backend/ide-backend-server'
- '../ide-backend/ide-backend-common'
extra-deps:
- Cabal-1.22.4.0
- cabal-install-1.22.6.0
compiler-check: newer-minor
resolver: lts-4.0
