flags:
  ide-backend-yesod: {}
packages:
- '.'
- '../ide-backend/ide-backend'
- '../ide-backend/ide-backend-rts'
- '../ide-backend/ide-backend-server'
- '../ide-backend/ide-backend-common'
- '../ide-backend-client'
extra-deps:
- hfsevents-0.1.5
- Cabal-1.22.3.0
resolver: nightly-2015-06-08
